name: goodtime
description: >-
  A complete time and date solution for Dart. Time periods: add and subtract
  months or years and land on the same day. Local and zoned dates and times.
  Arbitrary time zones. And more.

version: 0.5.0
homepage: https://github.com/pcekm/goodtime


environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  archive: ^3.3.7
  collection: ^1.17.1
  string_scanner: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
