name: tempo
description: >-
  A complete time and date solution that replaces Dart's core
  DateTime with a rich set of date and time classes, advanced
  arithmetic features and full time zone support.

version: 1.0.0
repository: https://github.com/pcekm/tempo

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  archive: ^3.3.7
  built_collection: ^5.1.1
  built_value: ^8.5.0
  collection: ^1.17.1
  meta: ^1.9.1
  string_scanner: ^1.2.0
  test: ^1.16.0

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.5.0
  dart_style: ^2.2.5
  lints: ^2.0.0
  path: ^1.8.3
